[package]
name = "mp4ameta_gen"
version = "0.7.0"
authors = ["Saecki <tobiasschmitz2001@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Code generation for common accessors of the mp4ameta crate."
repository = "https://github.com/Saecki/mp4ameta"
edition = "2021"

[dependencies]
toml = { version = "0.8.20", default-features = false, features = ["parse", "preserve_order"] }
